# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ];       then apt-get update && apt-get install -y python3 sudo bash ca-certificates iproute2 init && apt-get clean; fi;
RUN if [ $(command -v zypper) ];        then zypper refresh && zypper install -y python3 sudo bash python-xml iproute2 systemd-sysvinit && zypper clean -a; fi;
RUN if [ $(command -v apk) ];           then apk update && apk add --no-cache python3 sudo bash ca-certificates; fi;
RUN if [ $(command -v xbps-install) ];  then xbps-install -Syu && xbps-install -y python3 sudo bash ca-certificates iproute2 && xbps-remove -O; fi;
RUN if [ $(command -v swupd) ];         then swupd bundle-add python3-basic sudo iproute2; fi;
RUN if [ $(command -v dnf) ] && cat /etc/os-release | grep -q '^NAME=Fedora' && cat /etc/os-release | grep -q '^VERSION_ID=30'; then dnf makecache && dnf --assumeyes install python3 sudo python3-devel python3-dnf bash iproute && dnf clean all; fi;
RUN if [ $(command -v dnf) ] && cat /etc/os-release | grep -q '^NAME=Fedora'; then dnf makecache && dnf --assumeyes install python3 sudo python3-devel python*-dnf bash iproute && dnf clean all; fi;
RUN if [ $(command -v dnf) ] && cat /etc/os-release | grep -q '^NAME="CentOS Linux"' ; then dnf makecache && dnf --assumeyes install python36 sudo platform-python-devel python*-dnf bash iproute && dnf clean all && ln -s /usr/bin/python3 /usr/bin/python; fi;

RUN if [ $(command -v yum) && ! $(command -v dnf) ]; then yum makecache fast && yum install -y python3 sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; fi;
RUN if [ ! $(command -v python) ]; then ln -s /usr/bin/python3 /usr/bin/python; fi;
# Centos:8 + ansible 2.7 failed with error: "The module failed to execute correctly, you probably need to set the interpreter"
# Solution: ln -s /usr/bin/python3 /usr/bin/python

# Fedora:30 deprecated python2-dnf
# Solution: explicitly use python3-dnf instead
# https://github.com/ansible/ansible/issues/54855
# https://github.com/ansible/ansible/issues/59248

# Create `ansible` user with sudo permissions and membership in `DEPLOY_GROUP`
ENV ANSIBLE_USER=ansible DEPLOY_GROUP=deployer
#RUN if [ $(command -v dnf) ]; then SUDO_GROUP=wheel;export SUDO_GROUP; fi;
#RUN if [ $(command -v apt-get) ]; then SUDO_GROUP=sudo;export SUDO_GROUP; fi;
#ENV SUDO_GROUP=sudo
RUN set -xe \
  && groupadd -r ${ANSIBLE_USER} \
  && groupadd -r ${DEPLOY_GROUP} \
  && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
  && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
  && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
  && echo "%${SUDO_GROUP}        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
  
  #sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers