---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include debian_arm_server"
      include_role:
        name: "debian_arm_server"
      #ansible.builtin.import_tasks: "../../tasks/main.yml"
